symfony:
  extends:
    file: docker-compose-common.yml
    service: symfony
  environment:
    VIRTUAL_HOST: php-ci.docker
  volumes:
    - ~/Git:/git
    - ~/Code:/projects
  links:
    - "db:db"

db:
  extends:
    file: docker-compose-common.yml
    service: db
