symfony:
  build: dockerfiles/symfony
  volumes:
    - ./config/default_site.conf:/etc/apache2/sites-available/000-default.conf
    - ./config/mailcather.ini:/etc/php5/apache2/conf.d/99-mailcatcher.ini
    - ~/projects:/projects
  env_file:
    - ./config/docker/symfony.env.ini

db:
  image: mysql/mysql-server
  env_file:
    - ./config/docker/mysql.env.ini
  volumes:
    - ./mysql:/var/lib/mysql
    - ./backups.sh:/backups.sh
    - ./config/mysql_default.cnf:/etc/my.cnf
    - ./config/mysql:/etc/my.cnf.d
    - ./mysql_backups:/backups
