web:
  extends:
    file: docker-compose-common.yml
    service: web
  environment:
    VIRTUAL_HOST: php-ci.docker
  volumes:
    - ~/Git:/git
    - ~/Code:/projects
  links:
    - "db:db"

db:
  extends:
    file: docker-compose-common.yml
    service: db
  volumes:
    - ./server_conf/mysql_default.cnf:/etc/my.cnf
    - ./server_conf/mysql:/etc/my.cnf.d
