web:
  extends:
    file: docker-compose-common.yml
    service: web
  volumes:
    - ~/projects:/projects
  restart: always
  links:
    - "db:db"
db:
  extends:
    file: docker-compose-common.yml
    service: db
  restart: always
