symfony:
  extends:
    file: docker-compose-common.yml
    service: symfony
  volumes:
    - ~/Git:/git
    - ~/Code:/projects
  links:
    - "db:db"

db:
  extends:
    file: docker-compose-common.yml
    service: db
