web:
  extends:
    file: docker-compose-common.yml
    service: web
  environment:
    VIRTUAL_HOST: php-ci.tools.batandwa.me
  volumes:
    - ~/projects:/projects
  restart: always
  links:
    - "db:db"
db:
  extends:
    file: docker-compose-common.yml
    service: db
  restart: always